src/lolicon.pl

Lolicon but in Perl.

---

src/lolicon.go
src/lolicon.rb
src/lolicon.sh

Bash the lolicon.

---

src/lolicon.c
src/lolicon.d
src/lolicon.ll
src/lolicon.lua
src/lolicon.m

Kepнал ports.

---

src/lolicon.adb

Ported to ADA by Linn.

---

src/lolicon.cpp

Ported to C++ by Stnby.

---

src/lolicon.html

Don't know if you accept external PR but.
Ported from Rust to (almost) pure HTML and CSS because something called `html is not a programming language`.
Yet it's not a programming language but it has pseudo logic-gate with CSS.
Using CSS as a logic gate and HTML as a display, no JavaScript need.
Proof of Concept:

Ported to pure HTML&CSS

---

src/lolicon.java

Well, they are in coffee now...

Ported to JAVA

---

src/lolicon.js

Port Lolicon to Node.js

---

src/lolicon.java

sorry if it seems like i'm spamming this,  PR #19 had some problems so...

Fix spacing in lolicon.java

---

src/lolicon.bat

Porting lolicon to batch

---

src/lolicon.vim

Sorry for the lack of a `CallTheFbi` function, I wasn't able to parse the age value to a function for some reason...
anyways, I need help... 4 languages...

Porting lolicon to Vimscript

---

src/lolicon.kt

woohoo, the 13th language I port to! (i think!)

Porting lolicon to Kotlin

---

src/lolicon.jl

That's really just LUA being gay

Porting lolicon to Julia

---

src/lolicon.cobc

Yes, that language is a thing, google it.

Porting lolicon to COBOL

---

src/lolicon.swift

Ported Lolicon to Swift

---

src/lolicon.scala

Porting lolicon to Scala

---

src/lolicon.cs

Porting lolicon to C#

---

src/lolicon.bas

Porting lolicon to BASIC

---

src/lolicon.dart

Port lolicon to Dart

---

src/lolicon.scm

it took me 1 hour to learn how to use this fucking language to create this shit

Port lolicon to Scheme

---

src/lolicon.fs

Porting lolicon to F#

---

src/lolicon.f90

I realized I haven't ported this to any other languages in a while so...

lolicon in fortran

---

LICENSE
src/Lolicon.ts
src/LoliconException.ts
src/lolicon.adb
src/lolicon.bat
src/lolicon.d
src/lolicon.dart
src/lolicon.f90
src/lolicon.go
src/lolicon.java
src/lolicon.m
src/lolicon.py
src/lolicon.scm

Extra bytes removal; here we go~

Remove trailing whitespace

---

src/lolicon.vb

Visualize the lolicon in Visual Basic
